# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy to dev

on:
  push:
    branches: [ main ]
  workflow_dispatch:
#   pull_request:
#     branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 登录到服务器拉取代码重新启动
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /app/code/code-tools
            sdk use java 11.0.14.10.1-amzn
            git pull
            kill -9 $(lsof -t -sTCP:LISTEN -i:8020)
            mvn package -Pproduction
            nohup mvn spring-boot:run -Dvaadin.productionMode=true -Dchatgpt.api-key=${{ CHAT_GPT_API_KEY }} > code-tools.log &

          host: ${{ secrets.DEPLOY_HOST }}
          user: root
          pass: ${{ secrets.DEPLOY_PASSWORD }}
          args: "-tt"

      




















